name: Latex

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: .
          root_file: thesis.tex
          latexmk_shell_escape: true
      - name: Upload thesis as artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: thesis.pdf
